export const materialsLesson = [
   {
      id: 1,
      lesson: 'Lesson-1',
      lessonVideo: 'Видеоурок',
      presentation: 'Презентация',
      task: 'Задания',
      link: 'Ссылка',
      test: 'Тест',
   },
   {
      id: 2,
      lesson: 'Lesson-2',
      lessonVideo: 'Видеоурок',
      presentation: 'Презентация',
      task: 'Задания',
      link: 'Ссылка',
      test: 'Тест',
   },
   {
      id: 3,
      lesson: 'Lesson-3',
      lessonVideo: 'Видеоурок',
      presentation: 'Презентация',
      task: 'Задания',
      link: 'Ссылка',
      test: 'Тест',
   },
   {
      id: 4,
      lesson: 'Lesson-4',
      lessonVideo: 'Видеоурок',
      presentation: 'Презентация',
      task: 'Задания',
      link: 'Ссылка',
      test: 'Тест',
   },
]
