export const columns = [
   { id: 'id', label: 'ID' },
   { id: 'name', label: 'Имя Фамилия' },
   { id: 'group', label: 'Группа' },
   { id: 'format', label: 'Формат' },
   { id: 'numberPhone', label: 'Номер телефона' },
   { id: 'email', label: 'E-mail' },
]

export const data = [
   {
      id: 1,
      name: 'John Doe',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'narpaevd@gmail.com',
   },
   {
      id: 2,
      name: 'Jane Smith',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'narpaevd@gmail.com',
   },
   {
      id: 3,
      name: 'Bob Johnson',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'alikhan@gmail.com',
   },
   {
      id: 4,
      name: 'Alice Lee',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'alicelee@gmail.com',
   },
   {
      id: 5,
      name: 'Mark Anderson',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'mark.anderson@gmail.com',
   },
   {
      id: 6,
      name: 'Chris Evans',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'chrisevans@gmail.com',
   },
   {
      id: 7,
      name: 'Laura Taylor',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'laura.taylor@gmail.com',
   },
   {
      id: 8,
      name: 'Ryan Harris',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'ryanharris@gmail.com',
   },
   {
      id: 9,
      name: 'Olivia Martinez',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'olivia.martinez@gmail.com',
   },
   {
      id: 10,
      name: 'Michael Brown',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'michaelbrown@gmail.com',
   },
   {
      id: 11,
      name: 'Sophia Hernandez',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'sophia.hernandez@gmail.com',
   },
   {
      id: 12,
      name: 'David Wilson',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'david.wilson@gmail.com',
   },
   {
      id: 13,
      name: 'Ella Davis',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'ella.davis@gmail.com',
   },
   {
      id: 14,
      name: 'Andrew Clark',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'andrew.clark@gmail.com',
   },
   {
      id: 15,
      name: 'Grace Allen',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'grace.allen@gmail.com',
   },
   {
      id: 16,
      name: 'James Turner',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'james.turner@gmail.com',
   },
   {
      id: 17,
      name: 'Emma Scott',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'emma.scott@gmail.com',
   },
   {
      id: 18,
      name: 'William Hill',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'william.hill@gmail.com',
   },
   {
      id: 19,
      name: 'Ava Lewis',
      group: 'js-10-23',
      format: 'offline',
      numberPhone: 996708239366,
      email: 'ava.lewis@gmail.com',
   },
   {
      id: 20,
      name: 'Daniel Carter',
      group: 'js-10-23',
      format: 'online',
      numberPhone: 996708239366,
      email: 'daniel.carter@gmail.com',
   },
   // Add more users here with unique IDs
]
